name: delete_unused_image
owner: suica.dev
description: A CLI application delete unused image in normal flutter project.
repository: https://github.com/SuicaLondon/delete_unused_image
homepage: https://pub.dev/packages/delete_unused_image
version: 1.0.4
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  # path: ^1.8.0
  args: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
